use_frameworks!
platform :ios, '12.0'

target ‘HexaconExample’ do
   platform :ios, '12.0'
  #  pod 'Hexacon'
  # Dev locally easier:
   pod 'Hexacon', :path => '/Users/nathan/Documents/github/sweet-io/tmp/Hexacon'
end